# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/todo_db
spring.datasource.username=postgres
spring.datasource.password=Chirag@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: Show SQL parameters
spring.jpa.properties.hibernate.use_sql_comments=true

# Server Port (optional)
server.port=8080
